### ISSUE TITLE
[Bug]: Opening the charter in bopeebo crashes the game

### ISSUE THREAD

**Issue by thepercentageguy** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#20]
### Contact Details

thepercentageguy#1234

### What happened?

I tried opening the charter with bopeebo and it crashed.
Didn't test any other songs besides thorns which worked.

### Steps to reproduce

Go to bopeebo (on hard)
Press 7

### Version

3.6.0

**Comment by SpunBlue** [comment]
Opens fine for me.
