### ISSUE TITLE
[Bug]: SongBar Timer Is In Its Negatives On Song CountDown

### ISSUE THREAD

**Issue by DaRealDotZ** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#22]
### Contact Details

Im In The Discord Server (My Name Is DotZZ)

### What happened?

A Bug Flew Into My Room Then Crawled In My Pc

### Steps to reproduce

Load Up A Song

### Version

newest

**Comment by SpunBlue** [comment]
This is supposed to happen, I left it like this on purpose. I like negative numbers.

**Comment by DaRealDotZ** [comment]
Oh Alr Lmao
