### ISSUE TITLE
[Bug]: On HTML5 The Mods Week Library Is Not Found

### ISSUE THREAD

**Issue by DaRealDotZ** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#28]
### What happened?

When Testing The HTML5 Version I Loaded Up The Test Song And It Said "Missing Library: week69420"

### Steps to reproduce

load up the test song on the html5 version

### Version

newest version

**Comment by SpunBlue** [comment]
Sublime does not support HTML5
