### ISSUE TITLE
[Bug]: Ugh-swagmix Crashing

### ISSUE THREAD

**Issue by PortilizenHub** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#30]
### Contact Details

SussyCD#4057

### What happened?

When I was checking out the engine i wanted to check out ugh-swagmix, i thought it was gonns be a cool remix but when the song loaded the game crashed, idk if this is a issue cause im chromebook (90% possibility lol), or if this is an error in the code. I dunno.

### Steps to reproduce

select ugh-swagmix

### Version

3.10.0

**Comment by SpunBlue** [comment]
No one else has this issue.
