### ISSUE TITLE
[Bug]: App freezes when you enter Outdated Screen while having no internet connection.

### ISSUE THREAD

**Issue by DaRealDotZ** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#31]
### What happened?

Refer to title.

### Steps to reproduce

Disable your internet/WIFI.
Have an outdated build of the engine.
Load up the application on Android.

Exit the Title Screen.

### Version

Latest Version (PRE-RELEASE #2)

**Comment by SpunBlue** [comment]
Fixed this in the most lazy way possible.
