### ISSUE TITLE
[Bug]: When you try to enter the chart editor for a vanilla song, the game crashes.

### ISSUE THREAD

**Issue by DaRealDotZ** [SpunBlue/Friday-Night-Funkin-Sublime-Engine#32]
### Contact Details

Discord: Fishy MyBongles#9515

### What happened?

When I tried to chart a base FNF song, the game closed with no error.

### Steps to reproduce

Enter the chart editor on a vanilla song.

### Version

Latest

**Comment by SpunBlue** [comment]
Latest Pre-release or latest version?

**Comment by DaRealDotZ** [comment]
Pre-release.

**Comment by SpunBlue** [comment]
Once i'm done recovering from surgery i'll take a look.

**Comment by DaRealDotZ** [comment]
Sounds good!

**Comment by SpunBlue** [comment]
I do believe i have already fixed this issue in an unreleased version, I will check one i have the time.

**Comment by SpunBlue** [comment]
*Once
